#!/bin/bash
docker stop bme680-exporter
docker rm -f bme680-exporter
docker run -d \
  --net host \
  --name bme680-exporter \
  --restart always \
  -v /dev/i2c-1:/dev/i2c-1 \
  -e RUST_LOG=info \
  --privileged \
  bme680-exporter
